version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 520256696060.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=520256696060.dkr.ecr.us-east-1.amazonaws.com/testapp
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mytestapp","imageUri":"520256696060.dkr.ecr.us-east-1.amazonaws.com/testapp:latest"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json